from __future__ import annotations

import csv
import datetime as dt
from pathlib import Path


def run_finance(output_dir: str) -> dict[str, str]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    today = dt.date.today().isoformat()
    monthly_path = out / "monthly.csv"
    daily_path = out / "daily.csv"
    report_path = out / "report.md"

    with monthly_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["month", "income", "expense", "net"])
        writer.writeheader()
        writer.writerow({"month": today[:7], "income": 100000, "expense": 45000, "net": 55000})

    with daily_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["date", "income", "expense", "net"])
        writer.writeheader()
        writer.writerow({"date": today, "income": 3200, "expense": 1300, "net": 1900})

    report_path.write_text(
        "# Finance Report\n\n- Data generated by deterministic demo finance pipeline.\n"
        f"- Snapshot date: {today}.\n",
        encoding="utf-8",
    )

    return {
        "report": str(report_path),
        "daily_csv": str(daily_path),
        "monthly_csv": str(monthly_path),
    }


if __name__ == "__main__":
    run_finance("data/outputs/latest/finance")
